CREATE SEQUENCE SEQ_BAOLUU START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_BAOLUU_ID
BEFORE INSERT ON BAOLUU
FOR EACH ROW
BEGIN
    IF :NEW.MaBaoLuu IS NULL THEN
        :NEW.MaBaoLuu := 'BL' || TO_CHAR(SEQ_BAOLUU.NEXTVAL, 'FM000');
    END IF;
END;
/