CREATE SEQUENCE SEQ_BAOTRI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_BAOTRI_ID
BEFORE INSERT ON BAOTRI
FOR EACH ROW
BEGIN
    IF :NEW.MaPhieuBT IS NULL THEN
        :NEW.MaPhieuBT := 'BT' || TO_CHAR(SEQ_BAOTRI.NEXTVAL, 'FM000');
    END IF;
END;
/