CREATE SEQUENCE SEQ_CHECKIN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_CHECKIN_ID
BEFORE INSERT ON CHECKIN
FOR EACH ROW
BEGIN
    IF :NEW.MaCheckIn IS NULL THEN
        :NEW.MaCheckIn := 'CI' || TO_CHAR(SEQ_CHECKIN.NEXTVAL, 'FM00000');
    END IF;
END;
/