CREATE SEQUENCE SEQ_DANGKY_GOITAP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_DANGKY_GOITAP_ID
BEFORE INSERT ON DANGKY_GOITAP
FOR EACH ROW
BEGIN
    IF :NEW.MaDK IS NULL THEN
        :NEW.MaDK := 'DK' || TO_CHAR(SEQ_DANGKY_GOITAP.NEXTVAL, 'FM0000');
    END IF;
END;
/