CREATE SEQUENCE SEQ_GOITAP
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE OR REPLACE TRIGGER TRG_GOITAP_ID
BEFORE INSERT ON GOITAP
FOR EACH ROW
BEGIN
    IF :NEW.MaGoi IS NULL THEN
        :NEW.MaGoi := 'GT' || TO_CHAR(SEQ_GOITAP.NEXTVAL, 'FM000');
    END IF;
END;
/