CREATE SEQUENCE SEQ_HOADON
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE OR REPLACE TRIGGER TRG_HOADON_ID
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.MaHD IS NULL THEN
        :NEW.MaHD := 'HD' || TO_CHAR(SEQ_HOADON.NEXTVAL, 'FM0000'); 
    END IF;
END;
/