-- Tạo Sequence đếm số cho Hội viên
CREATE SEQUENCE SEQ_HOIVIEN
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

-- Tạo Trigger ghép tiền tố 'HV' với số từ Sequence
CREATE OR REPLACE TRIGGER TRG_HOIVIEN_ID
BEFORE INSERT ON HOIVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaHV IS NULL THEN
        :NEW.MaHV := 'HV' || TO_CHAR(SEQ_HOIVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/