CREATE SEQUENCE SEQ_HOIVIEN
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE OR REPLACE TRIGGER TRG_HOIVIEN_ID
BEFORE INSERT ON HOIVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaHV IS NULL THEN
        :NEW.MaHV := 'HV' || TO_CHAR(SEQ_HOIVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/