CREATE SEQUENCE SEQ_HUANLUYENVIEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_HUANLUYENVIEN_ID
BEFORE INSERT ON HUANLUYENVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaPT IS NULL THEN
        :NEW.MaPT := 'PT' || TO_CHAR(SEQ_HUANLUYENVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/