CREATE SEQUENCE SEQ_LICHTAP_PT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_LICHTAP_PT_ID
BEFORE INSERT ON LICHTAP_PT
FOR EACH ROW
BEGIN
    IF :NEW.MaLich IS NULL THEN
        :NEW.MaLich := 'LT' || TO_CHAR(SEQ_LICHTAP_PT.NEXTVAL, 'FM0000');
    END IF;
END;
/