CREATE SEQUENCE SEQ_LOPHOC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_LOPHOC_ID
BEFORE INSERT ON LOPHOC
FOR EACH ROW
BEGIN
    IF :NEW.MaLop IS NULL THEN
        :NEW.MaLop := 'LH' || TO_CHAR(SEQ_LOPHOC.NEXTVAL, 'FM000');
    END IF;
END;
/