CREATE SEQUENCE SEQ_NHANVIEN
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE OR REPLACE TRIGGER TRG_NHANVIEN_ID
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaNV IS NULL THEN
        :NEW.MaNV := 'NV' || TO_CHAR(SEQ_NHANVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/