CREATE SEQUENCE SEQ_THIETBI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_THIETBI_ID
BEFORE INSERT ON THIETBI
FOR EACH ROW
BEGIN
    IF :NEW.MaTB IS NULL THEN
        :NEW.MaTB := 'TB' || TO_CHAR(SEQ_THIETBI.NEXTVAL, 'FM000');
    END IF;
END;
/