CREATE SEQUENCE SEQ_VOUCHER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_VOUCHER_ID
BEFORE INSERT ON VOUCHER
FOR EACH ROW
BEGIN
    IF :NEW.MaVoucher IS NULL THEN
        :NEW.MaVoucher := 'VC' || TO_CHAR(SEQ_VOUCHER.NEXTVAL, 'FM000');
    END IF;
END;
/