CREATE OR REPLACE PROCEDURE SP_XOA_DANGKY_GOITAP (
    p_MaDK IN VARCHAR2
) AS
    v_MaHD VARCHAR2(10);
BEGIN
    SELECT MaHD INTO v_MaHD FROM DANGKY_GOITAP WHERE MaDK = p_MaDK;

    DELETE FROM DANGKY_GOITAP WHERE MaDK = p_MaDK;
    
    IF v_MaHD IS NOT NULL THEN
        DELETE FROM HOADON WHERE MaHD = v_MaHD;
    END IF;

    COMMIT;
END;
/