CREATE TABLE BAOLUU (
    MaBaoLuu VARCHAR2(10),
    MaDK VARCHAR2(10),
    NgayBatDauNghi DATE,
    NgayKetThucNghi DATE,
    LyDo NVARCHAR2(255),
    CONSTRAINT PK_BAOLUU PRIMARY KEY (MaBaoLuu),
    CONSTRAINT FK_BL_DK FOREIGN KEY (MaDK) REFERENCES DANGKY_GOITAP(MaDK)
);