CREATE TABLE BAOTRI (
    MaPhieuBT VARCHAR2(10),
    MaTB VARCHAR2(10),
    NgayBaoTri DATE,
    NoiDung NVARCHAR2(255),
    ChiPhi NUMBER(15, 2),
    CONSTRAINT PK_BAOTRI PRIMARY KEY (MaPhieuBT),
    CONSTRAINT FK_BT_TB FOREIGN KEY (MaTB) REFERENCES THIETBI(MaTB)
);