CREATE TABLE CHECKIN (
    MaCheckIn VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaDK VARCHAR2(10),
    ThoiGianVao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianRa TIMESTAMP,
    GhiChu NVARCHAR2(255),
    CONSTRAINT PK_CHECKIN PRIMARY KEY (MaCheckIn),
    CONSTRAINT FK_CI_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_CI_DK FOREIGN KEY (MaDK) REFERENCES DANGKY_GOITAP(MaDK)
);