-- 1. BẢNG GÓI TẬP
CREATE TABLE GOITAP (
    MaGoi VARCHAR2(10),
    TenGoi NVARCHAR2(100) NOT NULL,
    ThoiGianHieuLuc NUMBER(5),
    DonGia NUMBER(15, 2),
    MoTa NVARCHAR2(255),
    QuyenGoiTap NVARCHAR2(50),
    CONSTRAINT PK_GOITAP PRIMARY KEY (MaGoi)
);

-- 2. BẢNG VOUCHER (MÃ GIẢM GIÁ)
CREATE TABLE VOUCHER (
    MaVoucher VARCHAR2(20),
    TenVoucher NVARCHAR2(100),
    LoaiVoucher NVARCHAR2(50),
    PhanTramGiam NUMBER(5, 2),
    NgayHetHan DATE,
    GiaTriToiThieu NUMBER(15, 2),
    CONSTRAINT PK_VOUCHER PRIMARY KEY (MaVoucher)
);

-- 3. BẢNG THIẾT BỊ
CREATE TABLE THIETBI (
    MaTB VARCHAR2(10),
    TenTB NVARCHAR2(100),
    LoaiMay NVARCHAR2(50),
    NgayMua DATE,
    TinhTrang NVARCHAR2(50),
    ViTri NVARCHAR2(100),
    CONSTRAINT PK_THIETBI PRIMARY KEY (MaTB)
);

-- 4. BẢNG HỘI VIÊN (Đã bổ sung thêm cột SoBuoiPT phục vụ cho chức năng trừ buổi)
CREATE TABLE HOIVIEN (
    MaHV VARCHAR2(10),
    HoTen NVARCHAR2(100) NOT NULL,
    GioiTinh NVARCHAR2(10),
    NgaySinh DATE,
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(200),
    Email VARCHAR2(100),
    TinhTrangSK NVARCHAR2(255),
    NgayDangKy DATE DEFAULT SYSDATE,
    HangTV NVARCHAR2(20) DEFAULT 'Silver',
    TongChiTieu NUMBER(15, 2) DEFAULT 0,
    SoBuoiPT NUMBER(5) DEFAULT 0, -- Cột bổ sung thêm trong quá trình làm chức năng Lịch Tập
    CONSTRAINT PK_HOIVIEN PRIMARY KEY (MaHV)
);

-- 5. BẢNG NHÂN VIÊN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(10),
    HoTen NVARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR2(10),
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(200),
    ChucVu NVARCHAR2(50),
    LuongCB NUMBER(15, 2),
    NgayVaoLam DATE DEFAULT SYSDATE,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNV)
);

-- 6. BẢNG HUẤN LUYỆN VIÊN (Liên kết với Nhân viên)
CREATE TABLE HUANLUYENVIEN (
    MaPT VARCHAR2(10),
    ChuyenMon NVARCHAR2(100),
    BangCap NVARCHAR2(100),
    Rating NUMBER(2, 1),
    MaNV_LienKet VARCHAR2(10),
    CONSTRAINT PK_HUANLUYENVIEN PRIMARY KEY (MaPT),
    CONSTRAINT FK_PT_NHANVIEN FOREIGN KEY (MaNV_LienKet) REFERENCES NHANVIEN(MaNV)
);

-- 7. BẢNG TÀI KHOẢN HỆ THỐNG
CREATE TABLE TAIKHOAN (
    TenDN VARCHAR2(50),
    MatKhau VARCHAR2(255) NOT NULL,
    QuyenTruyCap NVARCHAR2(20),
    MaNV VARCHAR2(10),
    MaPT VARCHAR2(10),
    TrangThai NVARCHAR2(20),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TenDN),
    CONSTRAINT FK_TK_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_TK_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);

-- 8. BẢNG LỚP HỌC NHÓM
CREATE TABLE LOPHOC (
    MaLop VARCHAR2(10),
    TenLop NVARCHAR2(100),
    MaPT VARCHAR2(10),
    MoTa NVARCHAR2(255),
    SoLuongToiDa NUMBER(3),
    LichHoc NVARCHAR2(200),
    LoaiLop NVARCHAR2(50),
    CONSTRAINT PK_LOPHOC PRIMARY KEY (MaLop),
    CONSTRAINT FK_LOP_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);

-- 9. BẢNG HÓA ĐƠN
CREATE TABLE HOADON (
    MaHD VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaNV VARCHAR2(10),
    NgayLap DATE DEFAULT SYSDATE,
    TongTien NUMBER(15, 2),
    MaVoucher VARCHAR2(20),
    PhuongThucTT NVARCHAR2(50),
    TrangThaiHD NVARCHAR2(50),
    MaGoi VARCHAR2(10),
    CONSTRAINT PK_HOADON PRIMARY KEY (MaHD),
    CONSTRAINT FK_HD_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HD_VOUCHER FOREIGN KEY (MaVoucher) REFERENCES VOUCHER(MaVoucher),
    CONSTRAINT FK_HD_GOI FOREIGN KEY (MaGoi) REFERENCES GOITAP(MaGoi)
);

-- 10. BẢNG ĐĂNG KÝ GÓI TẬP
CREATE TABLE DANGKY_GOITAP (
    MaDK VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaGoi VARCHAR2(10),
    MaHD VARCHAR2(10),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    TrangThai NVARCHAR2(50),
    CONSTRAINT PK_DANGKY_GOITAP PRIMARY KEY (MaDK),
    CONSTRAINT FK_DK_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_DK_GOI FOREIGN KEY (MaGoi) REFERENCES GOITAP(MaGoi),
    CONSTRAINT FK_DK_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);

-- 11. BẢNG LỊCH TẬP PT (1-1)
CREATE TABLE LICHTAP_PT (
    MaLich VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaPT VARCHAR2(10),
    NgayTap DATE,
    KhungGio VARCHAR2(20),
    TrangThaiBuoiTap NVARCHAR2(50),
    CONSTRAINT PK_LICHTAP_PT PRIMARY KEY (MaLich),
    CONSTRAINT FK_LICH_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_LICH_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);

-- 12. BẢNG ĐĂNG KÝ LỚP HỌC (Sử dụng khóa chính tổ hợp)
CREATE TABLE DANGKY_LOPHOC (
    MaHV VARCHAR2(10),
    MaLop VARCHAR2(10),
    NgayDangKy DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DK_LOPHOC PRIMARY KEY (MaHV, MaLop),
    CONSTRAINT FK_DKLH_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_DKLH_LOP FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop)
);

-- 13. BẢNG BẢO LƯU GÓI TẬP
CREATE TABLE BAOLUU (
    MaBaoLuu VARCHAR2(10),
    MaDK VARCHAR2(10),
    NgayBatDauNghi DATE,
    NgayKetThucNghi DATE,
    LyDo NVARCHAR2(255),
    CONSTRAINT PK_BAOLUU PRIMARY KEY (MaBaoLuu),
    CONSTRAINT FK_BL_DK FOREIGN KEY (MaDK) REFERENCES DANGKY_GOITAP(MaDK)
);

-- 14. BẢNG CHECK-IN (Nhật ký ra vào)
CREATE TABLE CHECKIN (
    MaCheckIn VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaDK VARCHAR2(10),
    ThoiGianVao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianRa TIMESTAMP,
    GhiChu NVARCHAR2(255),
    CONSTRAINT PK_CHECKIN PRIMARY KEY (MaCheckIn),
    CONSTRAINT FK_CI_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_CI_DK FOREIGN KEY (MaDK) REFERENCES DANGKY_GOITAP(MaDK)
);

-- 15. BẢNG BẢO TRÌ THIẾT BỊ
CREATE TABLE BAOTRI (
    MaPhieuBT VARCHAR2(10),
    MaTB VARCHAR2(10),
    NgayBaoTri DATE,
    NoiDung NVARCHAR2(255),
    ChiPhi NUMBER(15, 2),
    CONSTRAINT PK_BAOTRI PRIMARY KEY (MaPhieuBT),
    CONSTRAINT FK_BT_TB FOREIGN KEY (MaTB) REFERENCES THIETBI(MaTB)
);