CREATE TABLE DANGKY_GOITAP (
    MaDK VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaGoi VARCHAR2(10),
    MaHD VARCHAR2(10),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    TrangThai NVARCHAR2(50),
    CONSTRAINT PK_DANGKY_GOITAP PRIMARY KEY (MaDK),
    CONSTRAINT FK_DK_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_DK_GOI FOREIGN KEY (MaGoi) REFERENCES GOITAP(MaGoi),
    CONSTRAINT FK_DK_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);