CREATE TABLE DANGKY_LOPHOC (
    MaHV VARCHAR2(10),
    MaLop VARCHAR2(10),
    NgayDangKy DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DK_LOPHOC PRIMARY KEY (MaHV, MaLop),
    CONSTRAINT FK_DKLH_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_DKLH_LOP FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop)
);