CREATE TABLE HOADON (
    MaHD VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaNV VARCHAR2(10),
    NgayLap DATE DEFAULT SYSDATE,
    TongTien NUMBER(15, 2),
    MaVoucher VARCHAR2(20),
    PhuongThucTT NVARCHAR2(50),
    TrangThaiHD NVARCHAR2(50),
    MaGoi VARCHAR2(10),
    CONSTRAINT PK_HOADON PRIMARY KEY (MaHD),
    CONSTRAINT FK_HD_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HD_VOUCHER FOREIGN KEY (MaVoucher) REFERENCES VOUCHER(MaVoucher),
    CONSTRAINT FK_HD_GOI FOREIGN KEY (MaGoi) REFERENCES GOITAP(MaGoi)
);