CREATE TABLE HOIVIEN (
    MaHV VARCHAR2(10),
    HoTen NVARCHAR2(100) NOT NULL,
    GioiTinh NVARCHAR2(10),
    NgaySinh DATE,
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(200),
    Email VARCHAR2(100),
    TinhTrangSK NVARCHAR2(255),
    NgayDangKy DATE DEFAULT SYSDATE,
    HangTV NVARCHAR2(20) DEFAULT 'Silver',
    TongChiTieu NUMBER(15, 2) DEFAULT 0,
    CONSTRAINT PK_HOIVIEN PRIMARY KEY (MaHV)
);