CREATE TABLE HUANLUYENVIEN (
    MaPT VARCHAR2(10),
    ChuyenMon NVARCHAR2(100),
    BangCap NVARCHAR2(100),
    Rating NUMBER(2, 1),
    MaNV_LienKet VARCHAR2(10),
    CONSTRAINT PK_HUANLUYENVIEN PRIMARY KEY (MaPT),
    CONSTRAINT FK_PT_NHANVIEN FOREIGN KEY (MaNV_LienKet) REFERENCES NHANVIEN(MaNV)
);