CREATE TABLE LICHTAP_PT (
    MaLich VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaPT VARCHAR2(10),
    NgayTap DATE,
    KhungGio VARCHAR2(20),
    TrangThaiBuoiTap NVARCHAR2(50),
    CONSTRAINT PK_LICHTAP_PT PRIMARY KEY (MaLich),
    CONSTRAINT FK_LICH_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_LICH_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);