CREATE TABLE LOPHOC (
    MaLop VARCHAR2(10),
    TenLop NVARCHAR2(100),
    MaPT VARCHAR2(10),
    MoTa NVARCHAR2(255),
    SoLuongToiDa NUMBER(3),
    SoLuongHienTai NUMBER(3) DEFAULT 0, 
    NgayTap NVARCHAR2(100),  
    KhungGio NVARCHAR2(50), 
    LoaiLop NVARCHAR2(50),
    CONSTRAINT PK_LOPHOC PRIMARY KEY (MaLop),
    CONSTRAINT FK_LOP_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);