CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(10),
    HoTen NVARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR2(10),
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(200),
    ChucVu NVARCHAR2(50),
    LuongCB NUMBER(15, 2),
    NgayVaoLam DATE DEFAULT SYSDATE,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNV)
);