CREATE TABLE TAIKHOAN (
    TenDN VARCHAR2(50),
    MatKhau VARCHAR2(255) NOT NULL,
    QuyenTruyCap NVARCHAR2(20),
    MaNV VARCHAR2(10),
    MaPT VARCHAR2(10),
    TrangThai NVARCHAR2(20),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TenDN),
    CONSTRAINT FK_TK_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_TK_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);