CREATE TABLE THIETBI (
    MaTB VARCHAR2(10),
    TenTB NVARCHAR2(100),
    LoaiMay NVARCHAR2(50),
    NgayMua DATE,
    TinhTrang NVARCHAR2(50),
    ViTri NVARCHAR2(100),
    CONSTRAINT PK_THIETBI PRIMARY KEY (MaTB)
);