
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BAOLUU';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BAOTRI';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHECKIN';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DANGKY_GOITAP';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GOITAP';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HOADON';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HOIVIEN';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HUANLUYENVIEN';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LICHTAP_PT';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOPHOC';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NHANVIEN';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_THIETBI';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VOUCHER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN 
         RAISE;
      END IF;
END;
/


CREATE SEQUENCE SEQ_BAOLUU START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_BAOLUU_ID
BEFORE INSERT ON BAOLUU
FOR EACH ROW
BEGIN
    IF :NEW.MaBaoLuu IS NULL THEN
        :NEW.MaBaoLuu := 'BL' || TO_CHAR(SEQ_BAOLUU.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_BAOTRI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_BAOTRI_ID
BEFORE INSERT ON BAOTRI
FOR EACH ROW
BEGIN
    IF :NEW.MaPhieuBT IS NULL THEN
        :NEW.MaPhieuBT := 'BT' || TO_CHAR(SEQ_BAOTRI.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_CHECKIN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_CHECKIN_ID
BEFORE INSERT ON CHECKIN
FOR EACH ROW
BEGIN
    IF :NEW.MaCheckIn IS NULL THEN
        :NEW.MaCheckIn := 'CI' || TO_CHAR(SEQ_CHECKIN.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_DANGKY_GOITAP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_DANGKY_GOITAP_ID
BEFORE INSERT ON DANGKY_GOITAP
FOR EACH ROW
BEGIN
    IF :NEW.MaDK IS NULL THEN
        :NEW.MaDK := 'DK' || TO_CHAR(SEQ_DANGKY_GOITAP.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_GOITAP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_GOITAP_ID
BEFORE INSERT ON GOITAP
FOR EACH ROW
BEGIN
    IF :NEW.MaGoi IS NULL THEN
        :NEW.MaGoi := 'GT' || TO_CHAR(SEQ_GOITAP.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_HOADON START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_HOADON_ID
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.MaHD IS NULL THEN
        :NEW.MaHD := 'HD' || TO_CHAR(SEQ_HOADON.NEXTVAL, 'FM000'); 
    END IF;
END;
/

CREATE SEQUENCE SEQ_HOIVIEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_HOIVIEN_ID
BEFORE INSERT ON HOIVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaHV IS NULL THEN
        :NEW.MaHV := 'HV' || TO_CHAR(SEQ_HOIVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_HUANLUYENVIEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_HUANLUYENVIEN_ID
BEFORE INSERT ON HUANLUYENVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaPT IS NULL THEN
        :NEW.MaPT := 'PT' || TO_CHAR(SEQ_HUANLUYENVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_LICHTAP_PT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_LICHTAP_PT_ID
BEFORE INSERT ON LICHTAP_PT
FOR EACH ROW
BEGIN
    IF :NEW.MaLich IS NULL THEN
        :NEW.MaLich := 'LT' || TO_CHAR(SEQ_LICHTAP_PT.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_LOPHOC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_LOPHOC_ID
BEFORE INSERT ON LOPHOC
FOR EACH ROW
BEGIN
    IF :NEW.MaLop IS NULL THEN
        :NEW.MaLop := 'LH' || TO_CHAR(SEQ_LOPHOC.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_NHANVIEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_NHANVIEN_ID
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaNV IS NULL THEN
        :NEW.MaNV := 'NV' || TO_CHAR(SEQ_NHANVIEN.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_THIETBI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_THIETBI_ID
BEFORE INSERT ON THIETBI
FOR EACH ROW
BEGIN
    IF :NEW.MaTB IS NULL THEN
        :NEW.MaTB := 'TB' || TO_CHAR(SEQ_THIETBI.NEXTVAL, 'FM000');
    END IF;
END;
/

CREATE SEQUENCE SEQ_VOUCHER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER TRG_VOUCHER_ID
BEFORE INSERT ON VOUCHER
FOR EACH ROW
BEGIN
    IF :NEW.MaVoucher IS NULL THEN
        :NEW.MaVoucher := 'VC' || TO_CHAR(SEQ_VOUCHER.NEXTVAL, 'FM000');
    END IF;
END;
/