--------------------------------------------------------
-- PHẦN 1: XÓA CÁC BẢNG CŨ (NẾU CÓ) ĐỂ TRÁNH LỖI TRÙNG LẶP
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BAOLUU CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE LICHTAP_PT CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CHECKIN CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DANGKY_LOPHOC CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DANGKY_GOITAP CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE HOADON CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE BAOTRI CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE TAIKHOAN CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE LOPHOC CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE HUANLUYENVIEN CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE HOIVIEN CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE THIETBI CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE VOUCHER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE GOITAP CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

--------------------------------------------------------
-- PHẦN 2: TẠO BẢNG DANH MỤC (KHÔNG CHỨA KHÓA NGOẠI)
--------------------------------------------------------

-- 1. BẢNG GÓI TẬP
CREATE TABLE GOITAP (
    MaGoi VARCHAR2(10),
    TenGoi NVARCHAR2(100) NOT NULL,
    ThoiGianHieuLuc NUMBER(5),
    DonGia NUMBER(15, 2),
    MoTa NVARCHAR2(255),
    QuyenGoiTap NVARCHAR2(50),
    CONSTRAINT PK_GOITAP PRIMARY KEY (MaGoi)
);

-- 2. BẢNG VOUCHER (MÃ GIẢM GIÁ)
CREATE TABLE VOUCHER (
    MaVoucher VARCHAR2(20),
    TenVoucher NVARCHAR2(100),
    LoaiVoucher NVARCHAR2(50),
    PhanTramGiam NUMBER(5, 2),
    NgayHetHan DATE,
    GiaTriToiThieu NUMBER(15, 2),
    CONSTRAINT PK_VOUCHER PRIMARY KEY (MaVoucher)
);

-- 3. BẢNG THIẾT BỊ
CREATE TABLE THIETBI (
    MaTB VARCHAR2(10),
    TenTB NVARCHAR2(100),
    LoaiMay NVARCHAR2(50),
    NgayMua DATE,
    TinhTrang NVARCHAR2(50),
    ViTri NVARCHAR2(100),
    CONSTRAINT PK_THIETBI PRIMARY KEY (MaTB)
);

-- 4. BẢNG HỘI VIÊN
CREATE TABLE HOIVIEN (
    MaHV VARCHAR2(10),
    HoTen NVARCHAR2(100) NOT NULL,
    GioiTinh NVARCHAR2(10),
    NgaySinh DATE,
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(200),
    Email VARCHAR2(100),
    TinhTrangSK NVARCHAR2(255),
    NgayDangKy DATE DEFAULT SYSDATE,
    HangTV NVARCHAR2(20) DEFAULT 'Silver',
    TongChiTieu NUMBER(15, 2) DEFAULT 0,
    CONSTRAINT PK_HOIVIEN PRIMARY KEY (MaHV)
);

-- 5. BẢNG NHÂN VIÊN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(10),
    HoTen NVARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR2(10),
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(200),
    ChucVu NVARCHAR2(50),
    LuongCB NUMBER(15, 2),
    NgayVaoLam DATE DEFAULT SYSDATE,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNV)
);

--------------------------------------------------------
-- PHẦN 3: TẠO BẢNG CÓ KHÓA NGOẠI CẤP 1
--------------------------------------------------------

-- 6. BẢNG HUẤN LUYỆN VIÊN (Liên kết với NHANVIEN)
CREATE TABLE HUANLUYENVIEN (
    MaPT VARCHAR2(10),
    ChuyenMon NVARCHAR2(100),
    BangCap NVARCHAR2(100),
    Rating NUMBER(2, 1),
    KinhNghiem NUMBER,
    MaNV_LienKet VARCHAR2(10),
    CONSTRAINT PK_HUANLUYENVIEN PRIMARY KEY (MaPT),
    CONSTRAINT FK_PT_NHANVIEN FOREIGN KEY (MaNV_LienKet) REFERENCES NHANVIEN(MaNV)
);

-- 7. BẢNG BẢO TRÌ (Liên kết với THIETBI)
CREATE TABLE BAOTRI (
    MaPhieuBT VARCHAR2(10),
    MaTB VARCHAR2(10),
    NgayBaoTri DATE,
    NoiDung NVARCHAR2(255),
    ChiPhi NUMBER(15, 2),
    CONSTRAINT PK_BAOTRI PRIMARY KEY (MaPhieuBT),
    CONSTRAINT FK_BT_TB FOREIGN KEY (MaTB) REFERENCES THIETBI(MaTB)
);

-- 8. BẢNG TÀI KHOẢN (Liên kết với NHANVIEN, HUANLUYENVIEN)
CREATE TABLE TAIKHOAN (
    TenDN VARCHAR2(50),
    MatKhau VARCHAR2(255) NOT NULL,
    QuyenTruyCap NVARCHAR2(20),
    MaNV VARCHAR2(10),
    MaPT VARCHAR2(10),
    TrangThai NVARCHAR2(20),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TenDN),
    CONSTRAINT FK_TK_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_TK_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);

-- 9. BẢNG HÓA ĐƠN (Liên kết với HOIVIEN, NHANVIEN, VOUCHER, GOITAP)
CREATE TABLE HOADON (
    MaHD VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaNV VARCHAR2(10),
    NgayLap DATE DEFAULT SYSDATE,
    TongTien NUMBER(15, 2),
    MaVoucher VARCHAR2(20),
    PhuongThucTT NVARCHAR2(50),
    TrangThaiHD NVARCHAR2(50),
    MaGoi VARCHAR2(10),
    CONSTRAINT PK_HOADON PRIMARY KEY (MaHD),
    CONSTRAINT FK_HD_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HD_VOUCHER FOREIGN KEY (MaVoucher) REFERENCES VOUCHER(MaVoucher),
    CONSTRAINT FK_HD_GOI FOREIGN KEY (MaGoi) REFERENCES GOITAP(MaGoi)
);

--------------------------------------------------------
-- PHẦN 4: TẠO BẢNG CÓ KHÓA NGOẠI CẤP 2 (Phụ thuộc vào các bảng trên)
--------------------------------------------------------

-- 10. BẢNG LỚP HỌC (Liên kết với HUANLUYENVIEN)
CREATE TABLE LOPHOC (
    MaLop VARCHAR2(10),
    TenLop NVARCHAR2(100),
    MaPT VARCHAR2(10),
    MoTa NVARCHAR2(255),
    SoLuongToiDa NUMBER(3),
    SoLuongHienTai NUMBER(3) DEFAULT 0,
    NgayTap NVARCHAR2(100),      
    KhungGio NVARCHAR2(50),   
    LoaiLop NVARCHAR2(50),
    CONSTRAINT PK_LOPHOC PRIMARY KEY (MaLop),
    CONSTRAINT FK_LOP_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);

-- 11. BẢNG ĐĂNG KÝ GÓI TẬP (Liên kết với HOIVIEN, GOITAP, HOADON)
CREATE TABLE DANGKY_GOITAP (
    MaDK VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaGoi VARCHAR2(10),
    MaHD VARCHAR2(10),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    TrangThai NVARCHAR2(50),
    CONSTRAINT PK_DANGKY_GOITAP PRIMARY KEY (MaDK),
    CONSTRAINT FK_DK_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_DK_GOI FOREIGN KEY (MaGoi) REFERENCES GOITAP(MaGoi),
    CONSTRAINT FK_DK_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);

-- 12. BẢNG LỊCH TẬP PT (Liên kết với HOIVIEN, HUANLUYENVIEN)
CREATE TABLE LICHTAP_PT (
    MaLich VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaPT VARCHAR2(10),
    NgayTap DATE,
    KhungGio VARCHAR2(20),
    TrangThaiBuoiTap NVARCHAR2(50),
    CONSTRAINT PK_LICHTAP_PT PRIMARY KEY (MaLich),
    CONSTRAINT FK_LICH_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_LICH_PT FOREIGN KEY (MaPT) REFERENCES HUANLUYENVIEN(MaPT)
);

--------------------------------------------------------
-- PHẦN 5: TẠO BẢNG CÓ KHÓA NGOẠI CẤP 3 (Phụ thuộc vào cấp 2)
--------------------------------------------------------

-- 13. BẢNG ĐĂNG KÝ LỚP HỌC (Liên kết với HOIVIEN, LOPHOC)
CREATE TABLE DANGKY_LOPHOC (
    MaHV VARCHAR2(10),
    MaLop VARCHAR2(10),
    NgayDangKy DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DK_LOPHOC PRIMARY KEY (MaHV, MaLop),
    CONSTRAINT FK_DKLH_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_DKLH_LOP FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop)
);

-- 14. BẢNG CHECK-IN (Liên kết với HOIVIEN, DANGKY_GOITAP)
CREATE TABLE CHECKIN (
    MaCheckIn VARCHAR2(10),
    MaHV VARCHAR2(10),
    MaDK VARCHAR2(10),
    ThoiGianVao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianRa TIMESTAMP,
    GhiChu NVARCHAR2(255),
    CONSTRAINT PK_CHECKIN PRIMARY KEY (MaCheckIn),
    CONSTRAINT FK_CI_HV FOREIGN KEY (MaHV) REFERENCES HOIVIEN(MaHV),
    CONSTRAINT FK_CI_DK FOREIGN KEY (MaDK) REFERENCES DANGKY_GOITAP(MaDK)
);

-- 15. BẢNG BẢO LƯU GÓI TẬP (Liên kết với DANGKY_GOITAP)
CREATE TABLE BAOLUU (
    MaBaoLuu VARCHAR2(10),
    MaDK VARCHAR2(10),
    NgayBatDauNghi DATE,
    NgayKetThucNghi DATE,
    LyDo NVARCHAR2(255),
    CONSTRAINT PK_BAOLUU PRIMARY KEY (MaBaoLuu),
    CONSTRAINT FK_BL_DK FOREIGN KEY (MaDK) REFERENCES DANGKY_GOITAP(MaDK)
);