CREATE OR REPLACE VIEW VW_CHART_REVENUE_GROWTH AS
WITH MonthSeries AS (
    SELECT 
        ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - (6 - LEVEL)) AS M_START,
        LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - (6 - LEVEL))) AS M_END
    FROM DUAL CONNECT BY LEVEL <= 6
)
SELECT 
    TO_NCHAR(N'T' || EXTRACT(MONTH FROM M_START)) AS NAME,
    NVL((SELECT SUM(TONGTIEN) FROM HOADON WHERE NGAYLAP >= M_START AND NGAYLAP <= M_END), 0) AS VALUE
FROM MonthSeries ORDER BY M_START ASC;

COMMIT;