CREATE OR REPLACE VIEW VW_CHART_MEMBER_GROWTH AS
WITH MonthSeries AS (
    SELECT 
        ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - (6 - LEVEL)) AS M_START,
        LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - (6 - LEVEL))) AS M_END
    FROM DUAL CONNECT BY LEVEL <= 6
)
SELECT 
    TO_NCHAR(N'T' || EXTRACT(MONTH FROM M_START)) AS NAME,
    (SELECT COUNT(*) FROM HOIVIEN WHERE NGAYDANGKY <= M_END) AS VALUE
FROM MonthSeries ORDER BY M_START ASC;