CREATE OR REPLACE VIEW VW_DASHBOARD_STATS AS
WITH RawStats AS (
    SELECT 
        (SELECT COUNT(*) FROM HOIVIEN) as total,
        (SELECT COUNT(*) FROM CHECKIN WHERE TRUNC(THOIGIANVAO) = TRUNC(SYSDATE)) as today_checkin,
        (SELECT NVL(SUM(TONGTIEN), 0) FROM HOADON WHERE TO_CHAR(NGAYLAP, 'MM/YYYY') = TO_CHAR(SYSDATE, 'MM/YYYY')) as monthly_rev,
        (SELECT COUNT(*) FROM HOIVIEN WHERE TO_CHAR(NGAYDANGKY, 'MM/YYYY') = TO_CHAR(SYSDATE, 'MM/YYYY')) as new_mem
    FROM DUAL
)
SELECT 
    total AS TONG_HOI_VIEN, 
    today_checkin AS CHECKIN_HOM_NAY, 
    monthly_rev AS DOANH_THU_THANG,
    TO_NCHAR(CASE WHEN total = 0 THEN '0' ELSE TO_CHAR(ROUND((new_mem/total)*100, 1)) END || N'%') AS TANG_TRUONG 
FROM RawStats;