CREATE OR REPLACE VIEW VW_EXPIRING_MEMBERS AS
SELECT 
    hv.HOTEN, 
    hv.SDT, 
    gt.TENGOI, 
    (TRUNC(dk.NGAYKETTHUC) - TRUNC(SYSDATE)) AS SO_NGAY_CON_LAI
FROM DANGKY_GOITAP dk
JOIN HOIVIEN hv ON dk.MAHV = hv.MAHV
JOIN GOITAP gt ON dk.MAGOI = gt.MAGOI
WHERE TRUNC(dk.NGAYKETTHUC) >= TRUNC(SYSDATE) 
  AND TRUNC(dk.NGAYKETTHUC) <= TRUNC(SYSDATE) + 10
  AND (dk.TRANGTHAI IS NULL OR dk.TRANGTHAI != N'Hết hạn')
ORDER BY SO_NGAY_CON_LAI ASC;