CREATE OR REPLACE VIEW VW_PACKAGE_DISTRIBUTION AS
SELECT 
    gt.TENGOI AS NAME,
    COUNT(dk.MADK) AS VALUE
FROM GOITAP gt
LEFT JOIN DANGKY_GOITAP dk ON gt.MAGOI = dk.MAGOI
GROUP BY gt.TENGOI
ORDER BY VALUE DESC;