CREATE OR REPLACE VIEW VW_RECENT_ACTIVITIES AS
SELECT * FROM (
    SELECT TO_NCHAR('Hội viên mới') as TIEU_DE, TO_NCHAR(HOTEN || N' đã đăng ký') as MO_TA, NGAYDANGKY as THOI_GIAN, TO_NCHAR('text-blue-500') as MAU FROM HOIVIEN
    UNION ALL
    SELECT TO_NCHAR('Thanh toán'), TO_NCHAR(N'Hóa đơn ' || MAHD || N': ' || TONGTIEN), NGAYLAP, TO_NCHAR('text-yellow-500') FROM HOADON
    UNION ALL
    SELECT TO_NCHAR('Check-in'), TO_NCHAR(N'Mã ' || MAHV || N' vừa check-in'), THOIGIANVAO, TO_NCHAR('text-green-500') FROM CHECKIN
    ORDER BY THOI_GIAN DESC
) FETCH FIRST 4 ROWS ONLY;