CREATE OR REPLACE VIEW VW_REPORT_REVENUE_GROUPING AS
SELECT 
    NVL(gt.TENGOI, 'TỔNG CỘNG (GRAND TOTAL)') AS TEN_GOI,
    COUNT(dk.MADK) AS SO_LUOT_DANG_KY,
    SUM(hd.TONGTIEN) AS TONG_DOANH_THU
FROM HOADON hd
JOIN DANGKY_GOITAP dk ON hd.MAHD = dk.MAHD -- SỬA THÀNH HD.MAHD = DK.MAHD
JOIN GOITAP gt ON dk.MAGOI = gt.MAGOI
GROUP BY ROLLUP(gt.TENGOI);