CREATE OR REPLACE TRIGGER TRG_CHECK_NGAYBAOTRI
BEFORE INSERT OR UPDATE ON BAOTRI
FOR EACH ROW
DECLARE
    v_NgayMua DATE;
BEGIN
    SELECT NGAYMUA INTO v_NgayMua FROM THIETBI WHERE MATB = :NEW.MATB;
    IF :NEW.NGAYBAOTRI < v_NgayMua THEN
        RAISE_APPLICATION_ERROR(-20001, N'Lỗi: Ngày bảo trì không được diễn ra trước ngày mua máy (' || TO_CHAR(v_NgayMua, 'DD/MM/YYYY') || ')!');
    END IF;
END;
/