CREATE OR REPLACE TRIGGER TRG_CALC_EXPIRY
BEFORE INSERT ON DANGKY_GOITAP
FOR EACH ROW
DECLARE
    v_ThoiHan NUMBER;
BEGIN
    SELECT ThoiGianHieuLuc INTO v_ThoiHan FROM GOITAP WHERE MaGoi = :NEW.MaGoi;
    IF :NEW.NgayKetThuc IS NULL THEN
        :NEW.NgayKetThuc := :NEW.NgayBatDau + v_ThoiHan;
    END IF;
END;
/