CREATE OR REPLACE TRIGGER TRG_CHECK_CHECKIN
BEFORE INSERT OR UPDATE ON CHECKIN
FOR EACH ROW
BEGIN
    IF :NEW.ThoiGianRa IS NOT NULL AND :NEW.ThoiGianRa <= :NEW.ThoiGianVao THEN
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi: Thời gian ra phải sau thời gian vào.');
    END IF;
END;
/