CREATE OR REPLACE FUNCTION F_TINH_CHI_PHI_BAO_TRI_MAY (
    p_MaTB IN VARCHAR2
) RETURN NUMBER AS
    v_TongChiPhi NUMBER := 0;
    v_CheckTonTai NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_CheckTonTai FROM THIETBI WHERE MaTB = p_MaTB;
    IF v_CheckTonTai = 0 THEN
        RETURN 0;
    END IF;

    SELECT NVL(SUM(ChiPhi), 0) INTO v_TongChiPhi 
    FROM BAOTRI 
    WHERE MaTB = p_MaTB;

    RETURN v_TongChiPhi;
END;
/