CREATE OR REPLACE TYPE TYPE_REVENUE_ROW AS OBJECT (
    TEN_GOI NVARCHAR2(100),
    SO_LUOT NUMBER,
    TONG_DOANH_THU NUMBER
);
/
CREATE OR REPLACE TYPE TYPE_REVENUE_TABLE AS TABLE OF TYPE_REVENUE_ROW;
/

CREATE OR REPLACE FUNCTION FN_GET_REVENUE_REPORT(p_TimeFilter IN VARCHAR2)
RETURN TYPE_REVENUE_TABLE PIPELINED
IS
BEGIN
    FOR rec IN (
        SELECT NVL(gt.TENGOI, 'TỔNG CỘNG (GRAND TOTAL)') AS TEN_GOI,
               COUNT(dk.MADK) AS SO_LUOT,
               SUM(hd.TONGTIEN) AS TONG_DOANH_THU
        FROM HOADON hd
        JOIN DANGKY_GOITAP dk ON hd.MAHD = dk.MAHD
        JOIN GOITAP gt ON dk.MAGOI = gt.MAGOI
        WHERE (p_TimeFilter = 'ALL')
           OR (p_TimeFilter = 'MONTH' AND TO_CHAR(hd.NGAYLAP, 'MM/YYYY') = TO_CHAR(SYSDATE, 'MM/YYYY'))
           OR (p_TimeFilter = 'YEAR' AND TO_CHAR(hd.NGAYLAP, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY'))
        GROUP BY ROLLUP(gt.TENGOI)
    ) LOOP
        PIPE ROW(TYPE_REVENUE_ROW(rec.TEN_GOI, rec.SO_LUOT, rec.TONG_DOANH_THU));
    END LOOP;
    RETURN;
END;
/