CREATE OR REPLACE TYPE TYPE_STAT_ROW AS OBJECT (
    TONG_HOI_VIEN NUMBER,
    CHECKIN_HOM_NAY NUMBER,
    DOANH_THU_THANG NUMBER
);
/
CREATE OR REPLACE TYPE TYPE_STAT_TABLE AS TABLE OF TYPE_STAT_ROW;
/

CREATE OR REPLACE FUNCTION FN_GET_DASHBOARD_STATS(p_TimeFilter IN VARCHAR2)
RETURN TYPE_STAT_TABLE PIPELINED
IS
    v_tong_hv NUMBER;
    v_checkin NUMBER;
    v_doanh_thu NUMBER;
BEGIN
    -- Số check-in luôn là của ngày hôm nay
    SELECT COUNT(*) INTO v_checkin FROM CHECKIN WHERE TRUNC(THOIGIANVAO) = TRUNC(SYSDATE);
    
    -- Xử lý rẽ nhánh logic thống kê tùy theo tham số truyền vào
    IF p_TimeFilter = 'MONTH' THEN
        SELECT COUNT(*) INTO v_tong_hv FROM HOIVIEN WHERE TO_CHAR(NGAYDANGKY, 'MM/YYYY') = TO_CHAR(SYSDATE, 'MM/YYYY');
        SELECT NVL(SUM(TONGTIEN), 0) INTO v_doanh_thu FROM HOADON WHERE TO_CHAR(NGAYLAP, 'MM/YYYY') = TO_CHAR(SYSDATE, 'MM/YYYY');
    ELSIF p_TimeFilter = 'YEAR' THEN
        SELECT COUNT(*) INTO v_tong_hv FROM HOIVIEN WHERE TO_CHAR(NGAYDANGKY, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY');
        SELECT NVL(SUM(TONGTIEN), 0) INTO v_doanh_thu FROM HOADON WHERE TO_CHAR(NGAYLAP, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY');
    ELSE
        SELECT COUNT(*) INTO v_tong_hv FROM HOIVIEN;
        SELECT NVL(SUM(TONGTIEN), 0) INTO v_doanh_thu FROM HOADON;
    END IF;
    
    PIPE ROW(TYPE_STAT_ROW(v_tong_hv, v_checkin, v_doanh_thu));
    RETURN;
END;
/